language: erlang
notifications:
  email:
    - engineering@2600hz.com
    - operations@2600hz.com
  irc:
    channels:
      - "irc.freenode.org#2600hz-dev"

otp_release:
  - 18.2
  - 19.1

sudo: required

addons:
  apt:
    packages:
      - xsltproc

cache:
  apt: true

before_install:
  - set -e

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x ./rebar3
  - export PATH=$PATH:$PWD

script:
  - rebar3 compile
  - DEBUG=1 rebar3 as test eunit
  - # make compile-test
  - # make eunit
  - make deps
  - ERLC_OPTS='-DPROPER' make compile-test
  - make eunit

after_success:
  - if [[ "$TRAVIS_REPO_SLUG" == '2600hz/kazoo' ]]; then make coverage-report; fi
